### ISSUE TITLE
Add usage instructions to README

### ISSUE THREAD

**Issue by wolftune** [Curly-Mo/swingify#1]
Thanks

**Comment by Curly-Mo** [comment]
Added simple commandline usage and updated the readme 7985ed8572a2e295d15b4794ffe58580925a22ea
If you are just interested in using it check out the hosted version at http://musinformatics.com/swingify

**Comment by wolftune** [comment]
Aha!! I knew about that but didn't know if this was the same thing!

**Comment by wolftune** [comment]
that commandline instruction is a great step. For those who don't use Python scripts regularly, is there anything to note about installing?
